# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket                      = "tf-state-bucket9999"
    dynamodb_table              = "tf-locks"
    encrypt                     = true
    key                         = "./terraform.tfstate"
    region                      = "us-east-1"
    skip_credentials_validation = false
    skip_metadata_api_check     = false
    skip_region_validation      = false
  }
}
